# Generated by Django 5.2.7 on 2025-10-27 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('emoji', models.CharField(default='🌱', max_length=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='avatares/')),
                ('nivel_requerido', models.IntegerField(default=1)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Avatar',
                'verbose_name_plural': 'Avatares',
                'ordering': ['nivel_requerido'],
            },
        ),
        migrations.CreateModel(
            name='Vivero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=300)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('horario', models.CharField(default='Lunes a Viernes 8am-5pm', max_length=200)),
                ('especies_disponibles', models.TextField(help_text='Lista de especies separadas por comas')),
                ('destacado', models.BooleanField(default=False, help_text='Viveros patrocinadores')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vivero',
                'verbose_name_plural': 'Viveros',
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('tipo_terreno', models.CharField(choices=[('urbano', 'Urbano'), ('rural', 'Rural'), ('montaña', 'Montaña'), ('ribera', 'Ribera'), ('parque', 'Parque')], max_length=20)),
                ('descripcion', models.TextField()),
                ('recomendaciones', models.TextField(help_text='Especies recomendadas y consejos')),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Zona de Siembra',
                'verbose_name_plural': 'Zonas de Siembra',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField(default=0)),
                ('nivel', models.IntegerField(default=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('avatar_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.avatar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='Siembra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='siembras/%Y/%m/')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('especie', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField(blank=True, max_length=500)),
                ('puntos_otorgados', models.IntegerField(default=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('validada', 'Validada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('fecha_siembra', models.DateTimeField(auto_now_add=True)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('notas_admin', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siembras', to=settings.AUTH_USER_MODEL)),
                ('validada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Siembra',
                'verbose_name_plural': 'Siembras',
                'ordering': ['-fecha_siembra'],
            },
        ),
    ]
