# Generated by Django 5.2.7 on 2025-11-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_verificacion_oxygen'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona',
            name='auto_generada',
            field=models.BooleanField(default=False, help_text='Zona generada automáticamente por concentración de siembras'),
        ),
        migrations.AddField(
            model_name='zona',
            name='radio_km',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Radio de cobertura en kilómetros', max_digits=5),
        ),
        migrations.AddField(
            model_name='zona',
            name='total_siembras',
            field=models.IntegerField(default=0, help_text='Total de siembras en esta zona'),
        ),
    ]
